### ISSUE TITLE
Error running create-react-library

### ISSUE THREAD

**Issue by sentry0** [transitive-bullshit/create-react-library#10]
This is what I'm seeing:

```
$ create-react-library
/usr/lib/node_modules/create-react-library/index.js:10
module.exports = async () => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by sentry0** [comment]
Needed to upgrade to v8.10.0 of node...I was on v6.9.1

**Comment by transitive-bullshit** [comment]
Makes sense -- glad you figured it out.

I'm curious if there's any way to enforce the version of node, as package.json [engines](https://github.com/transitive-bullshit/create-react-library/blob/master/package.json#L16) doesn't seems to only be a suggestion?

**Comment by sentry0** [comment]
That's too bad, I totally missed the engines entry.

Maybe it's worth putting a note in the docs about it?

**Comment by transitive-bullshit** [comment]
@sentry0 I've added support to the CLI for node >= 4 in `v2.2.0`, which seems to be the standard at the moment for version support among common node CLIs. This was more difficult than I thought, but it was an interesting learning experience 💯 

Please let me know if you run into any issues using the CLI with Node v4 or v6.

**Comment by transitive-bullshit** [comment]
Scratch that; there appear to be issues when installing from npm, so I had to revert this change.  Will update this thread once I get node >= 4 support working.

**Comment by transitive-bullshit** [comment]
Added #16 to track CLI support for older versions of node.
