### ISSUE TITLE
@material-ui as external not working when importing the library!

### ISSUE THREAD

**Issue by jamalsoueidan** [transitive-bullshit/create-react-library#100]
For some reasons it's not working when building my library!

Simple component.
```javascript
import React from "react";
import { Button } from "@material-ui/core";

const Test = () => {
  return <div>jamal</div>;
};

export default Test;
```

In the application I'm using this simple component as a library, and getting can't resolve @material-ui.

```
Module not found: Can't resolve '@material-ui/core' in 'C:\Users\Jamal\reactjs\simple-api\global-components\dist'
```

I think I need to specify @material-ui as globals in my setup, and I tried that but it does not work.

I already use @material-ui/core in my application, so it's already installed in the node_modules/package.json.

I hope someone can direct me to the solution.

Thank you,

**Comment by killakirby** [comment]
In your `package.json`, do you have material-ui under `peerDependencies`?

**Comment by tchalvak** [comment]
To provide more info, run these commands:

‘npm list material-ui’
‘cat package.json | grep material-ui’

And post the output.

**Comment by transitive-bullshit** [comment]
As @killakirby said, make sure `material-ui` is listed under `peerDependencies` for your library, and any projects that use your library should have a compatible version of `material-ui` installed.
