### ISSUE TITLE
How to import ts-import-plugin?

### ISSUE THREAD

**Issue by samuelcastro** [transitive-bullshit/create-react-library#101]
First of all, thanks for this amazing lib!

Wondering how would I integrate [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin), which is a TS version of [babel-plugin-import](https://github.com/ant-design/babel-plugin-import), and if I setup it up through `.babelrc` using the typescript version of create-react-library, would it work as expected? I'm not sure whether you're using babel7 to compile ts.

Thanks.

**Comment by transitive-bullshit** [comment]
`v3` switched to using https://github.com/developit/microbundle, so I'd recommend following up there if this is still affecting anyone.

Thanks!
