### ISSUE TITLE
Should I set 'prop-types' package as peer or...?

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [transitive-bullshit/create-react-library#102]
Hello, i'm trying to create NPM package with `create-react-library`, almost everything going fine, and it even successfully was published. But i catched an error when my package was first time instaled from NPM and 'create-react-app' was runing as `yarn start`.
It says: "Module not found: Can't resolve 'prop-types' in '/var/www/node_modules/react-range-gallery/dist'"

![prop-types](https://user-images.githubusercontent.com/10127643/48851445-24183180-edbc-11e8-9c69-26e52aedc708.PNG)

Should i set 'prop-types' as dependency instead of peerDependencies to be incapsulate it while `yarn build` or `yarn publish` ? 
As well as Redux and other packages are needed...

**Comment by transitive-bullshit** [comment]
I would recommend adding `prop-types` and most other generic dependencies as `peerDependencies` of your library.

Same goes for `redux`, though I'd implore you to ask yourself if your library is complex enough to actually warrant `redux` or if `setState` would be significantly simpler. 99% of react libraries are not complex enough to warrant the usage of any external state management library (though I know this is an unpopular opinion).

**Comment by transitive-bullshit** [comment]
Agreed with @tchalvak though, if it's really small, there's nothing wrong with putting it in `dependencies` and bundling it with your library.

**Comment by Andrew-Dyachenko** [comment]
> Yes, prop-types is small enough that just having it in dependencies should be fine ( see material ui doing so https://github.com/mui-org/material-ui/blob/master/packages/material-ui/package.json )



> I would recommend adding `prop-types` and most other generic dependencies as `peerDependencies` of your library.
> 
> Same goes for `redux`, though I'd implore you to ask yourself if your library is complex enough to actually warrant `redux` or if `setState` would be significantly simpler. 99% of react libraries are not complex enough to warrant the usage of any external state management library (though I know this is an unpopular opinion).

Indeed. There's no sense to use complex Redux in my case. `setState` is enouth.
I'm using only helper from Redux: `import { compose } from 'redux'`

**Comment by Andrew-Dyachenko** [comment]
> Yes, prop-types is small enough that just having it in dependencies should be fine ( see material ui doing so https://github.com/mui-org/material-ui/blob/master/packages/material-ui/package.json )

As I see in `package.json` above, the main dependencies are in only `reacts` and `reacts-dom`, which are quite heavy, all the other packages are quietly added depending, which will be compiled into a bundle.

I correctly understand that the user should connect especially large packages on his own, but without this package, our package will not work anyway?

**Comment by Andrew-Dyachenko** [comment]
Well I put the main, not heavy dependences as _dependencies_ instead of _peerDependencies_ and there're no build exeptions now.
