### ISSUE TITLE
Tooling to build the example app in PRs

### ISSUE THREAD

**Issue by paulmelnikow** [transitive-bullshit/create-react-library#105]
It would be really helpful if projects created with this boilerplate had a way to build the example app in a PR.

I'm doing this using Zeit Now, though there are some other solutions. I think Netlify accomplishes something similar.

I'm running into some issues with yarn which are making this a little tricky at the moment.

**Comment by sag1v** [comment]
what do you mean by build the example App in a PR?

**Comment by paulmelnikow** [comment]
Take a look at paulmelnikow/react-boxplot#46. This was a dependency bump, but that's not important; it could be any change.

Each commit to the PR triggered a build on Zeit:

<img width="814" alt="screen shot 2018-12-02 at 11 38 44 pm" src="https://user-images.githubusercontent.com/1487036/49353416-7e9e7100-f68b-11e8-8fb0-cfe6aef61ddd.png">

These scripts were responsible for doing the work:

https://github.com/paulmelnikow/react-boxplot/commit/48200f09d1fdb8a4e1ca9e7fcfc07f7ce9441a11

The built app is deployed here:

https://react-boxplot-1zjo543qn.now.sh/

And inspectable copies of the build here:

https://react-boxplot-1zjo543qn.now.sh/dist/index.es.js

The benefit is that I can see the effect of the PR on the example app or the build very quickly, without having to run the build on my dev machine.

**Comment by paulmelnikow** [comment]
@transitive-bullshit and other folks who contribute here, would it be helpful to spell this out in a more formal RFC?

I'm using PR review apps in https://github.com/paulmelnikow/react-boxplot, https://github.com/mathisonian/react-editable-svg-label, and it's incredibly helpful.

**Comment by transitive-bullshit** [comment]
I think this is outside the scope of what CRL should be responsible for.
