### ISSUE TITLE
material-components-web-react

### ISSUE THREAD

**Issue by bruqui** [transitive-bullshit/create-react-library#107]
I'm having an issue with the scss includes in my dependent packages for [material-components-web](https://github.com/material-components/material-components-web) and [material-components-web-react](https://github.com/material-components/material-components-web-react). The sass is imported like this in their scss files... `@import "@material/switch/mdc-switch";`. The problem is that they don't add the `~` (tilde). The work around that I've found for this in create-react-app is to add `export SASS_PATH=./node_modules;` in front of the build, start, etc. in the scripts section of the package.json file. I have attempted this; however, I'm still seeing this error and wanted to see if there are any suggestions to fix this...

```
[!] (postcss plugin) Error: File to import not found or unreadable: @material/switch/mdc-switch.
src/Switch.scss
Error: File to import not found or unreadable: @material/switch/mdc-switch.
    at options.error (/Users/jbsmith/Projects/core-react-components/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by transitive-bullshit** [comment]
I would ask over at [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss).

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
