### ISSUE TITLE
className not working without using styles

### ISSUE THREAD

**Issue by mistyhx** [transitive-bullshit/create-react-library#110]
When I am building the component. The following method of importing css does not work

Method 1
```
import  "./index.css"

const Mycomponent =()=>
<div className="title">Title</div>
```

It seems that the compiler was not able to recognize className = "". If I define the `body{}` by `import "./index.css"`, it works fine. 

Instead, I need to use the styles method

Method2 
```
import styles from "./index.css"

const Mycomponent =()=>
<div className={styles.title}">Title</div>
```
It would be very difficult to use some external library, which rely on method 1 for styling. 
Is there a way to use method 1 instead of method 2 

It would probably be a rollup config issue? I set 
```
postcss({
      modules: false,
    }),
```
it is still not working.

**Comment by sag1v** [comment]
@mistyhx  Do you have an example?
I created a [demo repo](https://github.com/sag1v/test-css) with no modules, seems to work as expected.

**Comment by mistyhx** [comment]
Hi @sag1v  I cloned your test-css repo and changed the styling in your styles.css file , but there is not any new changes to component. These are the changes that I have.  Is it because I did not instal something globally? 

```
.test {
  display: flex;
  justify-content: right;
  align-content: center;
  margin: 2em auto;
  border: 2px solid #000;
  font-size: 0.5em;
  color: red;
}
```

**Comment by sag1v** [comment]
@mistyhx Strange, do you run `npm start` on both folders (`/src` and `/example`) ?

**Comment by sag1v** [comment]
As i mentioned in my previous comment, do you run `npm start` in the `src` folder as well as the `/example` folder?
It won't watch for changes if you don't

**Comment by mistyhx** [comment]
Yes, I have run both. It is super weird. I can see the terminal loading to compile the updates, but nothing gets updated.

**Comment by sag1v** [comment]
Indeed strange, according to your initial issue i understand that if you use the css modules approach eg: `styles.className` everything works as expected. Is that correct?

**Comment by mistyhx** [comment]
Yes it works correct with the modules configuration, but not with the approach that we are discussing here.

**Comment by sag1v** [comment]
Hmm maybe @egoist can help with this? as its probably a `rollup-plugin-postcss` thing.

**Comment by ChrisLowe-Takor** [comment]
I've ran into something similar.  You could try turning `sourcemap` off for postcss in `rollup.config.js`

```
postcss({
	  modules: false,
	  sourcemap: false,
    }),
```

**Comment by SrdjanCosicPrica** [comment]
Ran into the same problem in `2.6.7`.
Ran
`create-react-library`

`yarn start` in both `src/` and `example/`

Go into `src/index.tsx`

Just change the line
`import styles from './styles.css'` to `import './styles.css'`

and in the render function
`div className={styles.test}` to `div className='test'`


When using `styles.test` it works but I see in chrome dev tools that the className is different
![screenshot 2019-02-08 at 15 14 30](https://user-images.githubusercontent.com/15933115/52483732-e9e94f80-2bb4-11e9-8f22-0cd5159b933b.png)

while when trying to use `className='test'` I get
![screenshot 2019-02-08 at 15 14 49](https://user-images.githubusercontent.com/15933115/52483777-01283d00-2bb5-11e9-90d1-b15e872e492c.png)

**Comment by JMA12** [comment]
Are you able to come up with a solution for this?

**Comment by transitive-bullshit** [comment]
This should be fixed with the latest `v3` release.

`*.css` will use normal CSS styles while a `*.module.css` file with use CSS modules following CRA & microbundle's conventions.

Please open a new issue if you're still seeing errors.

**Comment by odenirdev** [comment]
Im facing the same problem

**Comment by IMPranshu** [comment]
One thing worked for me is using "class" instead of "classname". Try it hope it works for you as well
