### ISSUE TITLE
nesting library and/or usage with lerna?

### ISSUE THREAD

**Issue by gcloeval** [transitive-bullshit/create-react-library#111]
First of all, thank you very much for this project. It was highly productive way of working.

I am now wandering if I can consolidate some of my packages even more and if this tool can be used, perhaps alongside with lerna? I have never used it before so I am not sure how/if this library relates to lerna: 

Anways, can you recommend or if you know of a good example of efficient workflow for something along these hypothetical libraries similar to my project:

- x-search-core
  Library that has some core functionallity for managing redux state, running queries etc
- x-search-mui
   Library that has material ui implementation of some useful components (filters, sorters, result lists etc)
- x-search-mui-app
   CRA Example application for x-search-mui
- x-search-sui
    Semantic UI implementation of some useful components (filters, sorters, result listc etc)
- x-search-sui-app
   CRA Example application for x-search-sui

At the moment, what I am doing is basically running two instances of "create-react-library" - one for material + example, one for semantic + example. And I manually manage updates to the search-core.  It is not ideal, but I can live with it - but maybe it can be better?

Is there any way to have it configured so that when I make a change to the core, it triggers rebuilding of search-mui and  search-sui which (as they currently already do) further triggers also rebuilds of their corresponding example apps?

Let me know if you have any thoughts and thx

**Comment by transitive-bullshit** [comment]
`v3` switches to using `microbundle` which I would recommend checking out if you're still interested in this use case.
