### ISSUE TITLE
enforcing SemVer with semantic-release?

### ISSUE THREAD

**Issue by adekbadek** [transitive-bullshit/create-react-library#113]
What do you think about enforcing SemVer? IMO it would be of great value for any library. I can work on a PR implementing [`semantic-release`](https://semantic-release.gitbook.io), but first wanted to ask if that's something you'd consider.
The con is that semantic-release will force a special [commit message format](https://blog.logrocket.com/never-guess-about-project-history-again-31f65091f668), but the whole SemVer can be conditional (with an additional question in `inquirer`).
More on the whole setup [here](https://blog.logrocket.com/never-guess-about-project-history-again-31f65091f668).

**Comment by transitive-bullshit** [comment]
Would be a nice opt-in feature, but I think this is too opinionated for CRL and pretty easy for library authors to add and customize once they have their library up & running.

Thanks!
