### ISSUE TITLE
Faling tests

### ISSUE THREAD

**Issue by Sharlaan** [transitive-bullshit/create-react-library#116]
i just forked repo and launched tests, but 3 of them are failing :

2 because of permission rejection upon using npm link

> message: `Command failed: C:\\WINDOWS\\system32\\cmd.exe /q /s /c "npm link"

in : `lib » create-library » creating "my-test-library" using npm`

the 3rd fail is :
```
  lib » create-library » creating "no-git-library" using yarn

  D:\Mes Projets\create-react-library\lib\create-library.test.js:112

   111:     ret = await execa.shell('git rev-parse --git-dir', { cwd: root })
   112:     t.is(ret.stdout, opts.git ? '.git' : path.join(process.cwd(), '.git'))
   113:

  Difference:
  - 'D:/Mes Projets/create-react-library/.git'
  + 'D:\\Mes Projets\\create-react-library\\.git'
```

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
