### ISSUE TITLE
Typescript type imports not working

### ISSUE THREAD

**Issue by antegulin** [transitive-bullshit/create-react-library#121]
Typescript type imports are treated as ES imports when building.

```JSX
 import {HotKeys} from "react-hotkeys";
```
[!] Error: '**HotKeys**' is not exported by node_modules/react-hotkeys/index.es.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

 Any ideas on how to resolve this?

**Comment by antegulin** [comment]
Importing like this solves the issue
```jsx
 import * as ReactHotkeys from "react-hotkeys";
```

**Comment by ragurney** [comment]
Tagging onto this, I am having a similar issue with [@zendeskgarden/react-theming](https://github.com/zendeskgarden/react-components/tree/master/packages/theming). I'm getting:
```
Error: 'ThemeProvider' is not exported by node_modules/@zendeskgarden/react-theming/dist/index.js
```
I tried adding:
```
namedExports: {
  'node_modules/@zendeskgarden/react-theming/dist/index.js': ['ThemeProvider'],
},
```
But then I get 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ThemeProvider`.
```
:( 

Any ideas?
