### ISSUE TITLE
New library: react-wordart

### ISSUE THREAD

**Issue by yershalom** [transitive-bullshit/create-react-library#124]
Hi,

I just published a react library based on create-react-library.
Super easy and super fast! 🚀
Thanks!

https://github.com/yershalom/react-wordart

Cheers

**Comment by HurricaneInteractive** [comment]
Hey @yershalom, I created a project called [Made with CRL](https://made-with-crl.netlify.com/), you can submit a PR there and I'll add it to the list 😄

**Comment by yershalom** [comment]
Hi @HurricaneInteractive ,
Opened a PR!
