### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by JeanPSF** [transitive-bullshit/create-react-library#127]
I am not sure if this issue should be in here, in [Boilerplate Project](https://github.com/transitive-bullshit/react-modern-library-boilerplate/tree/feature/multiple-exports) or if it isn't even a issue and i am only too dumb to understand what is happening, sorry if i am in the wrong place, but....

i've succesfully run projects from both repositories the one i linked and this one, the problem i found is when creating a library starting from this one, and try to reach the other one (for import/export porpouses, since i want my library to simple export components) and i get stuck at the error : 

[!] (rpt2 plugin) Error: C:/Users/jeanp/Desktop/myProject/myProject/src/index.tsx(1,1): semantic error TS6192 All imports in import declaration are unused.
src\index.tsx
Error: C:/Users/jeanp/Desktop/myProject/myProject/src/index.tsx(1,1): semantic error TS6192 All imports in import declaration are unused.

index.tsx

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'

//Global css config
import styles from './styles.css'

//Components to export
import Input1 from './components/inputs/input-1/Input1'
import ThemeSwitcher from './components/buttons/theme-switcher/ThemeSwitcher'

export { Input1, ThemeSwitcher }
```

An observation is that when i created my project from this repository, following the hackermoon blog post i didn't end up with the babel and eslint configured in my project.

i've tried adding babel and eslint in dependencies and run npm i, didn't solve the problem, so i tried manually copying the .eslintrc and .babelrc file from the multiple export repository, but also without success.

I've also tried to comment lines 1,2 and 5, since i really dont use them, altough i plan on using the css, so i am not sure how this will works in the future, and i got a different error now:

[!] (rpt2 plugin) Error: C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/index.tsx(8,20): semantic error TS7016 Could not find a declaration file for module './components/inputs/input-1/Input1'. 'C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/components/inputs/input-1/Input1.js' implicitly has an 'any' type.
src\index.tsx
Error: C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/index.tsx(8,20): semantic error TS7016 Could not find a declaration file for module './components/inputs/input-1/Input1'. 'C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/components/inputs/input-1/Input1.js' implicitly has an 'any' type.

index.tsx
```
//import React, { Component } from 'react'
//import PropTypes from 'prop-types'

//Global css config
//import styles from './styles.css'

//Components to export
import Input1 from './components/inputs/input-1/Input1'
import ThemeSwitcher from './components/buttons/theme-switcher/ThemeSwitcher'

export { Input1, ThemeSwitcher }
```

Any tips?
Thank you for the attention.

**Comment by JeanPSF** [comment]
Me again, i went back to a point where the project was working, created a component, and tried to import/export only, it throws me back the error about types.

index.tsx
```
import Input1 from './components/inputs/input-1/Input1'
/**
 * @class ExampleComponent
 */

import * as React from 'react'

import styles from './styles.css'

export type Props = { text: string }

class ExampleComponent extends React.Component<Props> {
  render() {
    const {
      text
    } = this.props

    return (
      <div className={styles.test}>
        Example Component: {text}
      </div>
    )
  }
}

export { ExampleComponent, Input1 }
```

error:
[!] (rpt2 plugin) Error: C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/index.tsx(1,20): semantic error TS7016 Could not find a declaration file for module './components/inputs/input-1/Input1'. 'C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/components/inputs/input-1/Input1.js' implicitly has an 'any' type.
src\index.tsx
Error: C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/index.tsx(1,20): semantic error TS7016 Could not find a declaration file for module './components/inputs/input-1/Input1'. 'C:/Users/jeanp/Desktop/Emed/emed-3_0-lib-ui-web/src/components/inputs/input-1/Input1.js' implicitly has an 'any' type.

**Comment by JeanPSF** [comment]
package.json
```
{
  "name": "my-lib-project",
  "version": "1.0.0",
  "description": "my-lib-project",
  "author": "",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": ""
  },
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "jsnext:main": "dist/index.es.js",
  "engines": {
    "node": ">=8",
    "npm": ">=5"
  },
  "scripts": {
    "test": "cross-env CI=1 react-scripts-ts test --env=jsdom",
    "test:watch": "react-scripts-ts test --env=jsdom",
    "build": "rollup -c",
    "start": "rollup -c -w",
    "prepare": "npm run build",
    "predeploy": "cd example && npm install && npm run build",
    "deploy": "gh-pages -d example/build"
  },
  "peerDependencies": {
    "prop-types": "^15.5.4",
    "react": "^15.0.0 || ^16.0.0",
    "react-dom": "^15.0.0 || ^16.0.0",
    "bootstrap": "^4.2.1"
  },
  "devDependencies": {
    "@svgr/rollup": "^2.4.1",
    "@types/jest": "^23.1.5",
    "@types/react": "^16.3.13",
    "@types/react-dom": "^16.0.5",
    "babel-core": "^6.26.3",
    "babel-runtime": "^6.26.0",
    "cross-env": "^5.1.4",
    "gh-pages": "^1.2.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-scripts-ts": "^2.16.0",
    "rollup": "^0.62.0",
    "rollup-plugin-babel": "^3.0.7",
    "rollup-plugin-commonjs": "^9.1.3",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-peer-deps-external": "^2.2.0",
    "rollup-plugin-postcss": "^1.6.2",
    "rollup-plugin-typescript2": "^0.17.0",
    "rollup-plugin-url": "^1.4.0",
    "typescript": "^2.8.3"
  },
  "files": [
    "dist"
  ],
  "dependencies": {

  }
}
```

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
