### ISSUE TITLE
Adding npmrc to production build

### ISSUE THREAD

**Issue by tyler7771** [transitive-bullshit/create-react-library#133]
I'm currently writing a component library and am using Font Awesome 5 Pro in some of the components. I created a .npmrc file to hold the auth credentials for FA5Pro.

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=<AUTH TOKEN>
``` 

When installing the library to projects the install fails because credentials aren't added to the dist file. What do I need to be doing to make sure this file gets rolled up with the rest of the code?

**Comment by paulmelnikow** [comment]
I'm not sure this is possible with npm, so it'd be out of scope for the framework.

If FA is installed as a npm dependency, you could make a peer dependency, and instruct users to get their own account. Or they could add your credentials themselves, though it seems doubtful your credentials are allowed to be used by 3rd party users of a component library.

**Comment by tyler7771** [comment]
Fair enough, thanks for the response.

**Comment by transitive-bullshit** [comment]
Agreed with @paulmelnikow; this is more of an npm issue and not something that can or should be resolved by CRL.

Thanks!
