### ISSUE TITLE
`github-org-cards` - another example of a lib using `crl`

### ISSUE THREAD

**Issue by devth** [transitive-bullshit/create-react-library#137]
https://github.com/devth/github-org-cards

demo: https://devth.com/github-org-cards/

screenshot: 
![image](https://user-images.githubusercontent.com/86107/54131142-f688df80-43ce-11e9-975d-057b8899fa12.png)

**Comment by transitive-bullshit** [comment]
Thanks @devth! I've actually been looking for something like this related to recreating [github.dev](https://github.dev/) with React.

**Comment by devth** [comment]
Cool :) 

This is just the first iteration. Planning to add some improvements.
