### ISSUE TITLE
rpt2 Cannot find module *.svg

### ISSUE THREAD

**Issue by mpourismaiel** [transitive-bullshit/create-react-library#138]
I checked both rpt2 and svgr repositories, issues and anything I could get my hands on but can't seem to be able to fix this issue.

I'm trying to import some SVG files, both as React components and as url [according to this typing](https://github.com/transitive-bullshit/create-react-library/blob/master/template/typescript/src/typings.d.ts#L12) but I get TS2307 "semantic error Cannot find module" from rollup-plugin-typescript2. SVG files are imported using relative paths and the paths are correct (`../../assets/images/checkbox-empty.svg` exists for instance and it's a default import, should be returning a string).

Here's my rollup config (small edit):

```
import typescript from 'rollup-plugin-typescript2';
import commonjs from 'rollup-plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import postcss from 'rollup-plugin-postcss';
import resolve from 'rollup-plugin-node-resolve';
import url from 'rollup-plugin-url';
import svgr from '@svgr/rollup';

import pkg from './package.json';

export default {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      exports: 'named',
      sourcemap: true,
    },
    {
      file: pkg.module,
      format: 'es',
      exports: 'named',
      sourcemap: true,
    },
  ],
  plugins: [
    external(),
    postcss({
      modules: true,
    }),
    url(),
    svgr(),
    resolve(),
    typescript({
      rollupCommonJSResolveHack: true,
      clean: true,
    }),
    commonjs({
      include: 'node_modules/**',
      namedExports: {
        'node_modules/react-is/index.js': [
          'isElement',
          'isValidElementType',
          'ForwardRef',
        ],
      },
    }),
  ],
};
```

And here are my packages:

```
"rollup": "^1.6.0",
"rollup-plugin-babel": "^4.3.2",
"rollup-plugin-commonjs": "^9.2.1",
"rollup-plugin-node-resolve": "^4.0.1",
"rollup-plugin-peer-deps-external": "^2.2.0",
"rollup-plugin-postcss": "^2.0.3",
"rollup-plugin-typescript2": "^0.19.3",
"rollup-plugin-url": "^2.2.0",
```

Let me know if I should've posted this somewhere else. It looks like a bug to me but I'm not really sure what's happening.

**Comment by transitive-bullshit** [comment]
`v3` just released and switches to using https://github.com/developit/microbundle under the hood. If you're experiencing anything like this after upgrading to `v3`, please file an issue there.

Thanks!
