### ISSUE TITLE
New library: react-border-wrapper

### ISSUE THREAD

**Issue by Metroxe** [transitive-bullshit/create-react-library#139]
I used this library to create my own react library in typescript. Everything went very well and will use it again in the future.

I would appreciate having my repo [react-border-wrapper](https://github.com/Metroxe/react-border-wrapper) added to the list.

**Comment by transitive-bullshit** [comment]
Thanks @Metroxe -- looks really solid! 😄 

Will add it to the list when I do the next batch.
