### ISSUE TITLE
eslint error

### ISSUE THREAD

**Issue by seleckis** [transitive-bullshit/create-react-library#14]
I have this error in Atom while editing index.js: `Cannot find module 'eslint-config-standard-react'`.

**Comment by jonthomp** [comment]
Same issue here in Visual Studio Code so I presume its not editor specific https://github.com/jonthomp/react-tabler-components/issues/13

**Comment by transitive-bullshit** [comment]
There were a few eslint packages missing from the template's devDependencies.

See the updated version [here](https://github.com/transitive-bullshit/create-react-library/blob/master/template/package.json).

**Comment by jonthomp** [comment]
Thanks @transitive-bullshit, I think eslint-plugin-node and eslint-plugin-promise are also required? Adding those in resolves the missing packages but now I'm getting a configuration error - 'Configuration for rule "indent" is invalid: 	Value "[object Object]" should NOT have additional properties.'.

**Comment by transitive-bullshit** [comment]
I think you're right.  Will add those as well.

Regarding the configuration rule issue, where is this happening from? Did you copy over the new `.editorconfig` files or is this also related to `eslint`?

**Comment by transitive-bullshit** [comment]
Also, feel 100% free to use your own `eslint` preferences, as the template is just a guide.  I would like to fix any issues with the default config, though.

**Comment by jonthomp** [comment]
Yeah I have the new .editorconfig file too. The error is coming up in my VSCode output window, the full eslint startup goes like so:

[Info  - 18:44:33] ESLint server is running.
[Info  - 18:44:35] ESLint library loaded from: d:\Development\react-tabler-components\node_modules\eslint\lib\api.js
[Error - 18:44:36] d:\Development\react-tabler-components\node_modules\eslint-config-standard\index.js: 	Configuration for rule "indent" is invalid: 	Value "[object Object]" should NOT have additional properties.  Referenced from: D:\Development\react-tabler-components\.eslintrc

Oh yeah totally on the rolling my own, just figured I would help fix it up instead. May or may not decide to just use eslint-config-react-app

**Comment by transitive-bullshit** [comment]
I believe this should be fixed now. Please reopen a new issue if you're still having problems with the latest version of `create-react-library`.

Thanks!
