### ISSUE TITLE
Rollup doesn't recognise axios package.json

### ISSUE THREAD

**Issue by gchumillas** [transitive-bullshit/create-react-library#148]
After installing the [axios](https://github.com/axios/axios) package I got this error:

```js
node_modules/axios/package.json (2:8)
1: {
2:   "name": "axios",
           ^
3:   "version": "0.18.0",
4:   "description": "Promise based HTTP client for the browser and node.js",

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
That's because rollup "doesn't understand" the json format. The solution is to install [rollup-plugin-json](https://github.com/rollup/rollup-plugin-json) which converts json to es6.

But installing it by default would be a plus.

```bash
$ create-react-library --version
2.6.7
```

**Comment by transitive-bullshit** [comment]
I'm not sure about this, but this thread looks related & useful: https://github.com/rollup/rollup-plugin-commonjs/issues/28

**Comment by swatkins** [comment]
I was having the same issue, and that thread worked for me. Thanks!

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
