### ISSUE TITLE
Running react-styleguidist script causes webpack error

### ISSUE THREAD

**Issue by jibin23** [transitive-bullshit/create-react-library#150]
I have  `"react-styleguidist": "^9.0.8"` as a dev dependency. Running either `"styleguidist server"` or  `"styleguidist build"` causes the following error:

`Webpack 3 is not supported by Styleguidist, the minimum version is 4`

**Comment by transitive-bullshit** [comment]
This should be fixed by `v3` as it's switched to using https://github.com/developit/microbundle

Please open a new issue for `v3` if you're still experiencing errors && thanks!
