### ISSUE TITLE
sass support raise an error

### ISSUE THREAD

**Issue by daniele-zurico** [transitive-bullshit/create-react-library#153]
Hi all,
I just create a library with create-react-library and it works really well. However, I was looking to add scss support but when I rename in scss it raise an error.
These are the step I did:
- npm install node-sass --dev
("node-sass": "^4.12.0")
- src/helloWorld
 - HelloWorld.module.scss
 - HelloWorld.tsx:
       import styles from './HelloWorld.module.scss';

When I run npm start:
```
[!] (rpt2 plugin) Error: /Users/daniele/Documents/Projects/capgemini-conception/react-library/src/helloWorld/HelloWorld.tsx(2,20): semantic error TS2307 Cannot find module './HelloWorld.module.scss'.
```

I missed something?

**Comment by JayaKrishnaNamburu** [comment]
Hey @daniele-zurico here are the changes that you need to make.

In your roll up config, add this and install ``rollup-plugin-scss`` as your devDependency and remove the default ``postcss``
import scss from 'rollup-plugin-scss'

And in plugins
Replace ``postcss()`` with ``scss()``
~~~
plugins: [
    external(),
    scss(),
    url(),
    svgr(),
    resolve(),
    typescript({
      rollupCommonJSResolveHack: true,
      clean: true
    }),
    commonjs()
  ]
~~~

**Comment by mkmladja** [comment]
Hi guys, do you have any additional info on this? 
@JayaKrishnaNamburu This didn't worked for me

**Comment by hellomrbigshot** [comment]
> Hi guys, do you have any additional info on this?
> @JayaKrishnaNamburu This didn't worked for me

This didn't worked for me, either.

**Comment by hellomrbigshot** [comment]
I got it.
you just need to run
```
yarn add -D node-sass
```
then set rollup.config.js
```
postcss({
      modules: false
    }),
```
then you can
```
import './style.scss'
```
and it works!
@JayaKrishnaNamburu @mkmladja @daniele-zurico

**Comment by daniele-zurico** [comment]
I’m not sure that it will become compiled in the js then! If you want to double check when you inspect with dev tools your class will become something with weird letters.

**Comment by arkadiusz-wieczorek** [comment]
@hellomrbigshot yea, it works! :)
