### ISSUE TITLE
Outdated libraries

### ISSUE THREAD

**Issue by viniciuspalma** [transitive-bullshit/create-react-library#154]
This boilerplate are creating npm packages with some outdated libraries like react-scripts and rollup.

**Comment by transitive-bullshit** [comment]
Thanks for bringing this up 😄 

This is a known issue that we're working to fix in v2. See #136

**Comment by viniciuspalma** [comment]
Thanks I just wrote this, because I'm having some problems to upgrade the libraries.
And I'll try to help :+1:

**Comment by transitive-bullshit** [comment]
Thanks @viniciuspalma -- help is more than welcome :)
