### ISSUE TITLE
Problems installing graphql-request package

### ISSUE THREAD

**Issue by abhimanyuPathania** [transitive-bullshit/create-react-library#155]
Installing `graphql-request` starts giving following warning when we run the `example` application.
```
Compiled with warnings.

../dist/index.es.js
Module not found: Can't resolve 'encoding' in '/Users/abhimanyu/react/graphql-test/dist'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```
I am using the same `graphql-request` v1.8.2 in a webpack application and it works without warnings.

### Steps to reproduce
1. Fresh install using `npx create-react-library` (it was using v2.6.7 at time of writing)
2. `yarn add graphql-request`
3. `import { GraphQLClient } from 'graphql-request';` in `src/index.tsx`
4. Run the example application

**Comment by transitive-bullshit** [comment]
This should be fixed in `v3`.

Thanks!
