### ISSUE TITLE
New library: lay-it-out

### ISSUE THREAD

**Issue by christianheyn** [transitive-bullshit/create-react-library#156]
Hi,

I just published a module with create-react-library:
https://github.com/christianheyn/lay-it-out

Thank you for this cool tool. It is really easy and fast to start and publish stuff!

Best regards
Christian

**Comment by HurricaneInteractive** [comment]
Hey @christianheyn, I created a project called [Made with CRL](https://made-with-crl.netlify.com/), you can submit a PR there and I'll add it to the list 😄
