### ISSUE TITLE
How to use regular CSS styles from src

### ISSUE THREAD

**Issue by chrisdel101** [transitive-bullshit/create-react-library#158]
Hi,
I setup my components in the `/example` folder and ran it. It worked great but then I realized this would not work. I'm linking this project to another one where I want to import it and this needs to be in the root `/src` folder. From there is is being imported via `npm link`.  Or at least it didn't work in `/example` and it does work now from `/src`. But not the CSS.

I do not use CSS modules and even so, importing the `style.css` does not work since all the class names get changed. Just copying in my CSS fails. So where does my regular `styles.css` go, like it does in the `/example`?

My folder structure looks like this where `styles.css` is the css for the entire project. This CSS is already done so it must be used out of a single file. `Graph.jsx` gets imported into `index.js` which is linked to an outside app.
<img width="187" alt="Screen Shot 2019-06-19 at 4 24 17 PM" src="https://user-images.githubusercontent.com/14151974/59797929-f9894b00-92ae-11e9-912c-85ad37f1db26.png">

My `index.js` just looks like this
```
import Graph from './components/Graph.jsx'

export default Graph
```

Am I doing it wrong? It's possible I have it all backwards.

**Comment by ashleyisles** [comment]
Hey! Did you find a solution to this? I think I'm in the same boat you were.
