### ISSUE TITLE
[Feature request]: Update default template to use functional component

### ISSUE THREAD

**Issue by jsjoeio** [transitive-bullshit/create-react-library#160]
Hi there! 

First, thanks for making this! 🙏🏼

Second, would you be interested in a PR that updates the default template to create a functional component as opposed to a class component?

**Comment by transitive-bullshit** [comment]
While I don't personally agree with this direction by the React team, it is undoubtedly the direction that React is headed in, so I think this would be a good decision to incorporate into CRL v2.

Thanks for the suggestion && see #171 for more details.

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
