### ISSUE TITLE
css is not applying while working with ssr

### ISSUE THREAD

**Issue by gboy666** [transitive-bullshit/create-react-library#164]
Components creating using this lib works fine for normal rendering. but CSS not get applied to the component while working with SSR.

**Comment by gboy666** [comment]
Hi, Me again. while digging deeper into the issue I found that it uses 
[rollup-plugin-postcss](https://www.npmjs.com/package/rollup-plugin-postcss) for bundling CSS and CSS modules. which in turn uses [style-inject](https://github.com/egoist/style-inject#options) for injecting CSS on dom head(while the component is called). 

[style-inject](https://github.com/egoist/style-inject#options) uses this to early return in non-browser environment

```
if (!css || typeof document === 'undefined') return
```

That's why CSS doesn't work while using the library in SSR mode.

**Comment by gboy666** [comment]
A workaround to this is to extract your CSS separately for into a single CSS file and doesn't bundle it with the component, using this option

``` js
postcss({
  extract: true // or path to your CSS file for ex: 'dist/style.css' [string]
})
```
In my case, I am generating two different bundles * dist * and  * dist-ssr * one with CSS bundled with component and other with separate CSS for SSR mode

**Comment by transitive-bullshit** [comment]
We changed the way this is handled in `v3`. You now manually pull in the `css` file which should get around this.
