### ISSUE TITLE
How to use module css 

### ISSUE THREAD

**Issue by JMA12** [transitive-bullshit/create-react-library#167]
Seems like the styles are not applied when using 
```
 <div className='test'>
    Example Component: {text}
 </div>


```
instead needs to use this: 
 ```
<div className={styles.test}>
      Example Component: {text}
 </div>
```

Is there a way to use the first method?

**Comment by transitive-bullshit** [comment]
In your CSS file, you can use:

```css
:global(.test) {
  color: red;
}
```

which will not apply CSS modularization to the `.test` classname.

**Comment by zwhitchcox** [comment]
Where are the css files exported? Like how do I import them into a project, or are they just somehow bundled with the output javsacript?

**Comment by transitive-bullshit** [comment]
they’re bundled with the output JS and injected into the HTML head automatically by postcss.

**Comment by zwhitchcox** [comment]
Ok, thank you
