### ISSUE TITLE
How to enable environment variables

### ISSUE THREAD

**Issue by JMA12** [transitive-bullshit/create-react-library#168]
I am trying to use dotenv. But when I try to show the env variables in console, it only shows these:

`ENV:  
{NODE_ENV: "development", PUBLIC_URL: ""}
NODE_ENV: "development"
PUBLIC_URL: ""
__proto__: Object`

And didn't include my custom variables

**Comment by transitive-bullshit** [comment]
Please open an issue on https://github.com/developit/microbundle if you're having issues after upgrading to `v3`.

Thanks!

**Comment by ogheneovo12** [comment]
I  currently can't use environment variables, is that an issue with roll-up too
