### ISSUE TITLE
Poll: convert to single dependency and ability to eject?

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/create-react-library#17]
One of the nicest things about CRA is that most of the functionality is bundled into a single dependency, [react-scripts](https://www.npmjs.com/package/react-scripts) which makes updating your CRA apps with bugfixes and transitive dependency updates relatively simple.

Currently, `create-react-library` doesn't perform this type of bundling and instead opts to generate the full boilerplate each time you create a new library. This is already a huge time-saver, but it could possibly be better.

Generating the full boilerplate has the advantage of being simple and leaving more customization power in the hands of the library author. It has the disadvantage that long-term library updates and maintenance will be harder, especially if you're publishing a lot of react libraries. This is something that I've run into myself over the past few months.

The workaround would be to follow suit with CRA and bundle all of the dependencies for `create-react-library` templates into a single dependency, `react-library-scripts`, which would allow library authors to update their libraries more easily. This would also necessitate the ability to _eject_ from `react-library-scripts` in an analogous fashion to how CRA works.

I think there are definitely pros and cons to both, but I wanted to put it out there and see what people think.  Not expecting too many responses, but if you feel strongly for one approach or the other, please vote here and respond below.

Thanks!

[![](https://api.gh-polls.com/poll/01CBAJA140FKX488D8QHY7JFQ0/Convert%20to%20single%20dependency%20and%20ability%20to%20eject)](https://api.gh-polls.com/poll/01CBAJA140FKX488D8QHY7JFQ0/Convert%20to%20single%20dependency%20and%20ability%20to%20eject/vote)
[![](https://api.gh-polls.com/poll/01CBAJA140FKX488D8QHY7JFQ0/Keep%20functionality%20as-is)](https://api.gh-polls.com/poll/01CBAJA140FKX488D8QHY7JFQ0/Keep%20functionality%20as-is/vote)

**Comment by mergebandit** [comment]
I have built two dozen modules with CRL. I’ve had to edit each one of them. So unless you’re surfacing the config files / build files I vote keep as is.

**Comment by transitive-bullshit** [comment]
What are some of the most common edits you're making?

Most of the `react-library-scripts` functionality would be embedding the rollup config and all of the babel/eslint/rollup devDependencies.
