### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by sadsa** [transitive-bullshit/create-react-library#170]
Reading through the last few pull requests and issues, it looks like @transitive-bullshit has been a bit distant as of late. He has a good track record on contribution activity on GitHub (although the majority of that seems to be an automated script that continually makes nonsense commits to a random repo). @transitive-bullshit Can you please give us an update on whether you plan to continue development on this library?

**Comment by transitive-bullshit** [comment]
See #171.

Most of my work these days is unfortunately in private repos.
