### ISSUE TITLE
Not working with react Hooks

### ISSUE THREAD

**Issue by v4irajvimu** [transitive-bullshit/create-react-library#173]
Hi, 

is this compatible with latest react version by now. Hooks not working

**Comment by ivanjeremic** [comment]
On /example side it is working maybe but not on package side because hooks work with 16.8 and we have here only ^16.4.1

**Comment by valecj** [comment]
Hello @v4irajvimu  
You can try this:

`If you use react-hooks in your project, when you debug you example you may run into a exception Invalid Hook Call Warning. This issue explain the reason, your lib and example use different instance, one solution is rewrite the react path in your example package.json to 'file:../node_modules/react' or 'link:../node_modules/react'.`

**Comment by amsterdamharu** [comment]
I removed the following from package.json in root of the project:

    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-scripts": "^1.1.4",

That would break test and test:watch scripts but maybe test can be moved to another directory with it's own package.json same as example?

**Comment by baurine** [comment]
After changing the `"react": "^16.4.1"` to `"react": "file:../node_modules/react"`, we still need to run `npm install` again to update the node_modules.

```
  "dependencies": {
    "prop-types": "^15.6.2",
-   "react": "^16.4.1",
+   "react": "file:../node_modules/react",
```

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
