### ISSUE TITLE
Get Author Name and Package Name from URL

### ISSUE THREAD

**Issue by akash-joshi** [transitive-bullshit/create-react-library#175]
Since the CLI is asking for package name & author name and forming Github path from there, why not take the reverse approach ?

1. Ask for GitHub URL. ( fetch author-name, package-name, description from there )
2. Show Author prompt ( default pre-filled )
3. Show Package Name prompt ( default pre-filled )
4. Show Description prompt ( default pre-filled )

**Comment by transitive-bullshit** [comment]
The default is to have everything pre-filled. We only ask as a convenience.
