### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by goxr3plus** [transitive-bullshit/create-react-library#178]
Can we have a new release for React 16.8.6 and above ?

**Comment by SCasarotto** [comment]
I was also wondering if there was a plan to update this lib. There are a lot of deps that are very out of date.

**Comment by goxr3plus** [comment]
True :)

**Comment by transitive-bullshit** [comment]
I finally got around to giving CRL some much needed love with the release of `v3`.

I decided to use a minor fork of [microbundle](https://github.com/developit/microbundle) which should simplify the maintenance burden going forwards.

Also, very much still looking for maintainers to help out.
