### ISSUE TITLE
[Feature] react-complete-router

### ISSUE THREAD

**Issue by darklight9811** [transitive-bullshit/create-react-library#185]
I just made a package that used create-react-library, it's called [react-complete-router](https://github.com/aposoftworks/react-complete-router)! I'm fairly new to making libraries, so pardo n any mistakes I commit. This helped me so muuuuch, thanks for transitive-bullshit!

**Comment by transitive-bullshit** [comment]
I'm glad you found CRL useful 😄 

Thanks!
