### ISSUE TITLE
Create React Library not working with Styled Components

### ISSUE THREAD

**Issue by emmabostian** [transitive-bullshit/create-react-library#197]
Hey - just curious if integration with styled components is supported?

I keep getting a hooks error:

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/7671983/72810960-f4361980-3c5e-11ea-9cad-f75c3308ef43.png">

**Comment by Andycharalambous** [comment]
I have the same problem - it’s hooks in general I believe. Only way around it I found was to use yalc for adding dependency to component library from example app and run yalc publish and yalc push every time I make a change to my components. Very annoying and slow. Would love to know if there is a better way.

**Comment by beTTostd** [comment]
You need to add *styled-components* as *peerDependencies* and *babel-plugin-styled-components*  as *devDependencies* and put in *.babelrc*

*package.json*
``` json
{
...
  "peerDependencies": {
    "prop-types": "^15.5.4",
    "react": "^15.0.0 || ^16.0.0",
    "react-dom": "^15.0.0 || ^16.0.0",
    "styled-components": "^5.0.0"
  },
...
}
```

*.babelrc*

``` json
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "stage-0",
    "react"
  ],
  "plugins": ["babel-plugin-styled-components"]
}

```

This is an [example](https://github.com/beTTostd/create-react-library-with-styled-components)

> Note
> When you'll use your library you need to install *styled-components* in the project 

if you liked I can make a template like the *typescript template*

**Comment by emmabostian** [comment]
Super thanks!

**Comment by emmabostian** [comment]
YES please do make a template that would be INCREDIBLE.

**Comment by hectormerla** [comment]
I tried what @beTTostd said but It didn't work for me, does anyone have the same issue?

I tried with other react/react-dom versions (16.13.0), I tried with yarn resolutions but nothing seems to work.

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release.

Please open a new issue if you're still seeing errors.
