### ISSUE TITLE
Add support for nullish coalescing in Typescript

### ISSUE THREAD

**Issue by FredrikAugust** [transitive-bullshit/create-react-library#199]
Good day. I was wondering if you were planning to implement support for nullish-coalescing in the typescript template.

Any hack to make it work would also be greatly appreciated.

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release as we're using `microbundle` under the hood which I believe has support for this out of the box.

Let me know if that's not the case && thanks!
