### ISSUE TITLE
CLI doesn't work with scoped package

### ISSUE THREAD

**Issue by mergebandit** [transitive-bullshit/create-react-library#2]
If I'm creating a scoped package (e.g. `@my-awesome-org/dope-module`) the folder structure created is:
```
my-awesome-org/
  dope-module
```

Instead, this should be:
```
dope-module/
```

FWIW the `name` field in `package.json` works for this.

**Comment by transitive-bullshit** [comment]
Good call; should be fixed in `v1.4.3`.

**Comment by transitive-bullshit** [comment]
I'd recommend updating to `v2.1.0`.

**Comment by mergebandit** [comment]
FYI I can confirm this works.
