### ISSUE TITLE
simplify predeploy script

### ISSUE THREAD

**Issue by ekoeryanto** [transitive-bullshit/create-react-library#20]
I think it is better to run the script without `cd`-ing 
example:
`
"predeploy": "yarn --cwd example && yarn --cwd example run build",
`
or

`"predeploy": "npm --prefix example install && npm --prefix example run build",`

**Comment by transitive-bullshit** [comment]
Thanks @ekoeryanto. I'm on the fence on this one.

Is there any reason in particular you prefer to not use `cd`?  I'm trying to keep the template differences between yarn and npm as minimal as possible.

**Comment by ekoeryanto** [comment]
no, you can keep using `cd` if you like. and feel free to close this issue

**Comment by transitive-bullshit** [comment]
ok -- i definitely appreciate the thoughts -- keep 'em coming 👍
