### ISSUE TITLE
(Question): Switching the library to a react webapplication

### ISSUE THREAD

**Issue by netkuttappan** [transitive-bullshit/create-react-library#205]
This is more of a question: 
I am able successfully create a library using create-react-library
But for development purpose i need to run this library as a web application to visualize the functionality. How shall i make a library to act as application when running "start" command and on "build" command it should work as a package or library

**Comment by Oscarteg** [comment]
I would use storybook to display the component you create but if you want to use something like create-react-app you can create an example folder with `npx create-react-app example`.  In the package.json add your own package as a local dependency. 

https://stackoverflow.com/questions/14381898/local-dependency-in-package-json

**Comment by transitive-bullshit** [comment]
I like the idea, but this is not in scope for CRL. It makes sense for CRL to remain a CLI as most devs expect that. What you're proposing would work better as a separate project.

Thanks!
