### ISSUE TITLE
How to provide typescript definitions?

### ISSUE THREAD

**Issue by serendipity1004** [transitive-bullshit/create-react-library#207]
I have published [this](https://github.com/serendipity1004/kakao-map-react/tree/v1.0.0) library. However, when I load the library in typescript project, I don't get IDE auto completes for imports and props. How do I provide these?

**Comment by Oscarteg** [comment]
@serendipity1004  In the `typings.d.ts` you have to define your interfaces and functions like this for example if you have a Button component.

```
export interface ButtonProps {
  onClick: () => void;
}

declare function Button(props: ButtonProps);
``` 

At least that depends on the kind of components you want to expose. Maybe you need to do it differently. Check the documentation about declaration files. https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by transitive-bullshit** [comment]
Thanks @Oscarteg.

**Comment by eivindml** [comment]
Did you figure this out? I can't get it to export types.
