### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by VCuzmin** [transitive-bullshit/create-react-library#219]
Hello. I'm trying to import my own component, it's called Button and its code is as follows:
` import React from "react";
import PropTypes from "prop-types";
import cx from "classnames";

// material-ui components
import { Button, withStyles } from "@material-ui/core";

import buttonStyle from "assets/jss/components/common/buttonStyle";

function RegularButton({ ...props }) {
  const {
    classes,
    color,
    round,
    children,
    fullWidth,
    disabled,
    customClass,
    right,
    justIcon,
    size,
    wd,
    ...rest
  } = props;
  const btnClasses = cx({
    [classes[color]]: color,
    [classes.round]: round,
    [classes.fullWidth]: fullWidth,
    [classes.disabled]: disabled,
    [customClass]: customClass,
    [classes.right]: right,
    [classes.justIcon]: justIcon,
    [classes.wd]: wd,
    [classes[size]]: size
  });
  return (
    <Button {...rest} className={classes.button + " " + btnClasses}>
      {children}
    </Button>
  );
}

RegularButton.propTypes = {
  classes: PropTypes.object.isRequired,
  color: PropTypes.oneOf([
    "primary",
    "info",
    "success",
    "warning",
    "danger",
    "rose",
    "defaultNoBackground",
    "primaryNoBackground",
    "infoNoBackground",
    "successNoBackground",
    "warningNoBackground",
    "dangerNoBackground",
    "roseNoBackground",
    "white",
    "simple",
    "transparent"
  ]),
  round: PropTypes.bool,
  children: PropTypes.node,
  fullWidth: PropTypes.bool,
  disabled: PropTypes.bool,
  customClass: PropTypes.string,
  // make the button's min width to 160px
  wd: PropTypes.bool,
  // make the button smaller
  justIcon: PropTypes.bool,
  // button will float right
  right: PropTypes.bool,
  size: PropTypes.oneOf(["sm", "lg", "xs"])
};

export default withStyles(buttonStyle)(RegularButton); `

My **rollup.config.js** : 

![image](https://user-images.githubusercontent.com/40390118/78229219-5c637000-74d8-11ea-8ed1-c04ff5b0bbf4.png)

My **index.js** is:

![image](https://user-images.githubusercontent.com/40390118/78229323-82891000-74d8-11ea-8e03-86fea0840cc6.png)

When I execute **npm start** I come across with this error:
![image](https://user-images.githubusercontent.com/40390118/78228804-d5ae9300-74d7-11ea-9073-3d0d3708c69a.png)

Please help me. Thx

**Comment by transitive-bullshit** [comment]
I would recommend starting a new library with the newly released `v3` branch and copying over your code.

We unfortunately don't have the bandwidth to help with pre-`v3` issues or custom rollup configs.
