### ISSUE TITLE
Doesnt work well with styled components

### ISSUE THREAD

**Issue by vester-the-developer** [transitive-bullshit/create-react-library#22]
I have searched online for many different configs for making this compatible with styled-components and eventually, my terminal starts crashing. I am not a pro so it could be something really simple so this is more of seeking help that an issue.

**Comment by vester-the-developer** [comment]
Sorry it was my fail. I'm not used to roll-up and just had to used the
named exports with commonjs

**Comment by transitive-bullshit** [comment]
No worries -- mind sharing a short code snippet for future github issue travelers?

**Comment by abdullahceylan** [comment]
To use with styled-components, you may need to find `commonjs()` in `rollup.config.js` file and replace with:

```js
commonjs({
      namedExports: {
        'node_modules/react/index.js': [
          'cloneElement',
          'createContext',
          'Component',
          'createElement'
        ],
        'node_modules/react-dom/index.js': ['render', 'hydrate'],
        'node_modules/react-is/index.js': [
          'isElement',
          'isValidElementType',
          'ForwardRef'
        ]
      }
    })
```

**Comment by nxmohamad** [comment]
@abdullahceylan do you mind explaining what the edit does? :)
