### ISSUE TITLE
How to include css in individual components

### ISSUE THREAD

**Issue by rawbeans** [transitive-bullshit/create-react-library#222]
Using webpack, I was able to `import './myStyles.css'` within a component file to bundle styles with it.

How can I accomplish this with create-react-library and rollup?

**Comment by transitive-bullshit** [comment]
This is not currently supported.

I'd recommend opening an issue over at [microbundle](https://github.com/developit/microbundle) and tagging this issue.

**Comment by teehtheg** [comment]
@rawbeans , not sure whether it really understand your problem, but what you can do is use css modules, import them in any library component and apply the desired styles to your HTML. 

In the end, create-react-lib will create an index.css file in your build, which contains all the styles you applied. This index.css file can then be included in the react application, where you'd like to use the components from your react library.

**Comment by codingbycat** [comment]
I also want to import components when using them without having to import CSS modules separately

**Comment by fenyagg** [comment]
microbundle already supports inline css `--css inline` [link](https://github.com/developit/microbundle#all-cli-options-)

**Comment by transitive-bullshit** [comment]
I recommend using a different tool these days. See my [2022 update](https://github.com/transitive-bullshit/create-react-library#2022-update).
