### ISSUE TITLE
Use prepare instead of prepublish

### ISSUE THREAD

**Issue by cinderblock** [transitive-bullshit/create-react-library#229]
I believe using `prepare` is better than `prepublish` because it is also automatically run when installing the repository as a library.

Any thoughts on this issue?

https://github.com/transitive-bullshit/create-react-library/blob/91f77fa30ec7b6132ea2729bc217f417f81e62aa/template/typescript/package.json#L17
https://github.com/transitive-bullshit/create-react-library/blob/91f77fa30ec7b6132ea2729bc217f417f81e62aa/template/default/package.json#L17

PS. love this app!

**Comment by nsisodiya** [comment]
As of npm@5, prepublish scripts are deprecated.

**Comment by transitive-bullshit** [comment]
Let's switch to `prepare` then?
