### ISSUE TITLE
Is the Material-UI Example still relevant

### ISSUE THREAD

**Issue by simkessy** [transitive-bullshit/create-react-library#233]
I want to create a library that relies on Material-UI but the example is about 3 years old and using rollup instead of microbundle-crl. 

What's the proper approach, can the example be updated if it's not the right steps anymore?

**Comment by transitive-bullshit** [comment]
The same approach should work in terms of everything in `src/`. 

Please follow-up if you find any issues in practice.

**Comment by simkessy** [comment]
I don't understand what you mean by the same approach. 

Are you saying that using microbundle-crl can handle Material-UI and CSS or are you saying I should follow the example from 3 years ago?

**Comment by naveen4854** [comment]
@simkessy add material-ui as peer dependency for the library and use the components.
and wherever u are consuming the library install material-ui and continue using

**Comment by naveen4854** [comment]
@transitive-bullshit I want to bundle third-party library's components and their CSS(primereact) with my library's build.
