### ISSUE TITLE
Can not pass first step

### ISSUE THREAD

**Issue by polRk** [transitive-bullshit/create-react-library#239]
npx create-react-library

? Package Name @polRk/ui

And nothing...

**Comment by kosmiq** [comment]
I just found out that if you use any capitalized letters it seems to get stuck. Go all lower case and it seems to proceed fine. I guess it should throw an error regarding capitalized letters like npm init does, but it does not.

TLDR; use only lowercase (@ and / seem to be fine) and it will work.
