### ISSUE TITLE
[suggestion] Relative paths for deploying to different provider (Netlify, ...)

### ISSUE THREAD

**Issue by Pyrax** [transitive-bullshit/create-react-library#246]
I'd like to suggest setting [homepage in example/package.json](https://github.com/transitive-bullshit/create-react-library/blob/master/template/default/example/package.json#L3) to `"homepage": "."` as described [in CRA docs](https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths) for serving from different paths. This would result in assets paths to be relative to index.html. So, you could deploy to e.g. Netlify from their CLI without changing anything in the project.

I have verified that the default deploy-script with gh-pages still works after this change.

Could this cause any problems? I'd like to hear some opinions.

**Comment by transitive-bullshit** [comment]
I think this sounds great.
