### ISSUE TITLE
create-react-library works good for first time React library builder

### ISSUE THREAD

**Issue by emxsys** [transitive-bullshit/create-react-library#25]
The __create-react-library__ npm module really eased my entry into the React and npm space.  I'm glad you wrote it and I'm glad I found it.

The README file told me just about everything I needed to know to get up and running and start working right away. 

Thank you _very much_ for your open source work.

Here's my new React library: https://github.com/emxsys/worldwind-react-globe. 
Feel free to add it to your README if you'd like.

**Comment by tsiq-swyx** [comment]
i love it too!

**Comment by transitive-bullshit** [comment]
Thanks @emxsys and @tsiq-swyx -- the encouragement really helps :)

Just added worldwind-react-globe to the readme!
