### ISSUE TITLE
images and json??

### ISSUE THREAD

**Issue by KyleWiteck** [transitive-bullshit/create-react-library#256]
Looking for a way to add images and json files in the dist. 

I currently have 2 folders in src.

- src/images (has .gif, .svg , .png and .jpeg files)
- src/data (holds json files)

Is this available now, or is this a new feature that is needed?
If so, how would this work?
We are trying to use create-react-library for our business and would really love these options. 

Thanks,
Kyle

**Comment by psyycker** [comment]
Hi,
Are added to the dist all the files which are directly or indirectly linked to your main file. In that case, if you want to move your images/jsons files into the dist folder, they need to be imported/required by any JS file which is itself link in any way to the index file.
Let me know if it helped

**Comment by KyleWiteck** [comment]
This worked, thank you.

**Comment by psyycker** [comment]
Great! Could you close the issue? :smiley:
