### ISSUE TITLE
Deploying the example on Netlify

### ISSUE THREAD

**Issue by aaronshaf** [transitive-bullshit/create-react-library#26]
Has anyone figured out how to deploy the example folder (with the npm "link") on Netlify?

**Comment by transitive-bullshit** [comment]
I haven't used netlify, but you can definitely just remove the "npm link" and point to a normal npm module once published.

**Comment by transitive-bullshit** [comment]
Also, once the example is built, it's just a 100% normal static website. You can adjust the `homepage` property in example/package.json to point to the domain where it'll be deployed and then use the npm [serve](https://github.com/zeit/serve) module as your package.json start script pointing to the built example source in `example/build`.

This is what I do when deploying to `now.sh` which should be very similar to netlify.
