### ISSUE TITLE
Generated code not consistent with the examples

### ISSUE THREAD

**Issue by Northshoot** [transitive-bullshit/create-react-library#28]
Hey,

Thanks for creting this! Awesome starting point.

I encounter inconsistencies in what boilerplate is generated and where you do into depth with examples https://github.com/transitive-bullshit/react-modern-library-boilerplate.

Among other things, rollups are never brought up in the mentioned example. Any timeline for updating them?

Cheers!

**Comment by transitive-bullshit** [comment]
Thanks for the interest @Northshoot & sorry for taking so long to respond.

Are you talking about the multiple exports and material-ui example branches? Or are you talking about the manual library creation?

**Comment by Northshoot** [comment]
I meant that in code example you don't have rolups:
[](https://github.com/transitive-bullshit/react-modern-library-boilerplate/tree/master/example)

but you talk about it in the [blog](https://hackernoon.com/publishing-baller-react-modules-2b039d84bce7)  

It would be just great to have working example what matches blog.

**Comment by transitive-bullshit** [comment]
Aye, that blog post is pretty old at this point. It does, however, have the same exact layout as the template create-react-library uses, including its use of rollup.

In any case, I'll be publishing a newer blog post soon, so stay tuned :)
