### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by mikecousins** [transitive-bullshit/create-react-library#29]
I'm getting this error when I try to use my published library that I created using create-react-library. Any idea what might cause this?

**Comment by transitive-bullshit** [comment]
Can you include a link to your module's source?

`fs` is a node-only module, so it's likely that either your library or one of its dependencies is not compatible with the browser and is trying to use the `fs` module.

**Comment by mikecousins** [comment]
Hmm, interesting. I'm trying a ground-up rewrite of my react-pdf-js library using your package.

Here's the source: https://github.com/mikecousins/react-pdf-js

It's a pretty simple project currently as I've started with a barebones library and I'll slowly add the features back in.

**Comment by mikecousins** [comment]
Hmm, yeah, my index.es.js is getting an `import fs from 'fs';` at the top. Any idea what would be putting that in?

**Comment by transitive-bullshit** [comment]
It's coming from `pdfjs-dist`. If you move this to a peer-dependency, things may just work since your usage would then correctly pickup the [browser](https://github.com/mozilla/pdfjs-dist/blob/master/package.json#L21-L26) portion of your dependency.

**Comment by mikecousins** [comment]
Then all my users would have to include it as a dependency though which I kind of wanted to avoid. Hmm. Any idea what's causing it in pdfjs-dist?

**Comment by mikecousins** [comment]
I'm guessing to fix this I'd need to eject and make a custom webpack.config?

**Comment by transitive-bullshit** [comment]
That's going to be a very rocky path.

I would recommend either my previous suggestion (peer-dep), since bundling such a large dependency alongside a react component is rarely a good idea.

Alternatively, you could try changing your `rollup.config.js` to have this line:
```js
resolve({
  browser: true
}),
```

which should include only browser-compatible modules in your bundle.

**Comment by mikecousins** [comment]
Yeah I put out a version already with it as a peer dependency and it seems to be working fine, other than having to get all my users to add another dependency. I'll give the other one a try and see what works best. Any downsides to the second approach?

**Comment by transitive-bullshit** [comment]
Large, complicated dependencies which already expose browser-compatible builds are generally better suited to be peer-deps so users can control which version they're using and upgrade or downgrade accordingly.

**Comment by mikecousins** [comment]
Sounds good, thanks for your help!

**Comment by transitive-bullshit** [comment]
No problem -- thanks for trying out create-react-library, and let me know if you run into any more issues 👍
