### ISSUE TITLE
rollup watches only first change

### ISSUE THREAD

**Issue by gadi246** [transitive-bullshit/create-react-library#30]
Working on Intelij, rollup watch catches only the first change in library src code...
solved via https://github.com/rollup/rollup-watch/issues/4 
but it doesn't seem like a robust solution.

**Comment by transitive-bullshit** [comment]
Interesting; I've definitely never run into this issue and have used create-react-library with dozens of projects over the past few months.

As this is a rollup issue, please post there, and if you find a solution that works for you, cross-post back here for others who may run into the same thing in the future.

Or just recompile when you make changes like back in the day ;-)

**Comment by tsiq-swyx** [comment]
"back in the day"?! what, are we going to hand-create our react libraries
like barbarians too? get outta here :)

**Comment by transitive-bullshit** [comment]
@tsiq-swyx hahah

If anyone else experiences this, please report it here along with your editor / platform / node version. If it's a pervasive issue, we'll have more leverage when bringing it up with the rollup team.

**Comment by Tommos0** [comment]
Experiencing this also. 
- Webstorm 2018.1.3
- Linux (debian testing)
- node 10.4.0
- rollup 0.57.1

**Comment by transitive-bullshit** [comment]
Closing this for now as this seems to be an issue unrelated to create-react-library. Please follow up with [rollup](https://github.com/rollup/rollup-watch/issues/4) if you encounter this bug.
