### ISSUE TITLE
How to add less loader or less support in src library ?

### ISSUE THREAD

**Issue by RavenColEvol** [transitive-bullshit/create-react-library#301]

**Comment by RavenColEvol** [comment]
Package already have rollup-plugin-postcss library which already provides less and sass support directly .

**Comment by N1ck0lay** [comment]
to use Less css you need:
1. npm i less --save-dev (in the root folder)
2. add "--css-modules false" to your **build** and **start** commands, so you will have:
    "build": "microbundle-crl --no-compress --format modern,cjs **--css-modules false**",
    "start": "microbundle-crl watch --no-compress --format modern,cjs **--css-modules false**"
    
3. create Button.js and styles.less files and import less file to Button.js with **import './styles.less'**
and you are ready to go!
