### ISSUE TITLE
got error on windows 10

### ISSUE THREAD

**Issue by ats1999** [transitive-bullshit/create-react-library#315]
```js
C:\Users\Rahul kumar\desktop\Projects\tui-t>npx create-react-library tui
npm ERR! code ENOLOCAL
npm ERR! Could not install from "kumar\AppData\Roaming\npm-cache\_npx\12164" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rahul kumar\AppData\Roaming\npm-cache\_logs\2021-01-06T01_46_20_794Z-debug.log
Install for [ 'create-react-library@latest' ] failed with code 1

C:\Users\Rahul kumar\desktop\Projects\tui-t>npx create-react-library
npm ERR! code ENOLOCAL
npm ERR! Could not install from "kumar\AppData\Roaming\npm-cache\_npx\15712" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rahul kumar\AppData\Roaming\npm-cache\_logs\2021-01-06T01_47_15_262Z-debug.log
Install for [ 'create-react-library@latest' ] failed with code 1
```

**Comment by rjptechsolutions** [comment]
- Delete node_modules folder,
- Delete package-lock.json
- Do the following changes in package.json 
`
"dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4",
    "your-lib-name": "file:.."
  },
  "devDependencies": {},
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }

`
Do these changes and write your own library /package name in place "your-lib-name"
This will fix the issue.
