### ISSUE TITLE
[Error: EACCES: permission denied, scandir '/home/xxx/.dbus']

### ISSUE THREAD

**Issue by AXeL-dev** [transitive-bullshit/create-react-library#316]
Hey,

I was trying to create a new library using the `create-react-library` command, but it always fail with the following error:

![image](https://user-images.githubusercontent.com/30635693/103883421-796b4600-50dd-11eb-8dc5-969934e8c816.png)

I tried to google it & i came across some similar issues on other projects:

https://github.com/atom/tree-view/issues/898

https://github.com/atom/tree-view/pull/761

Still i'm not sure if the issue is directly related to the project or to one of its dependencies.

Below further informations about my dev environment:
- OS: Ubuntu 18.04
- create-react-library version: 3.1.1

Thanks!

**Comment by vitorboccio** [comment]
looks like it's a permission issue with your own computer.
try running the command with sudo. `sudo create-react-library`
