### ISSUE TITLE
npm publish dummy - needed?

### ISSUE THREAD

**Issue by worthlutz** [transitive-bullshit/create-react-library#32]
I do not understand the following:

`Because you're using npm, you'll need to publish a dummy version of ${lib.name} first before you can "npm link" your package into the example app.`

I created a new directory (test-it) with `create-react-library` using `npm` as the Package Manager.

In the `test-it` directory I ran

`npm start`

Then in the `example` directory I ran

```
npm link test-it
npm install
npm start
```

I did not have to publish anything.

Am I missing something?

Note your instructions in the terminal at the end of `create-react-library` do not mention the need to 
run `npm install` in the `example` directory.  Until I did this I had problems.  Peer dependencies may be needed to be installed in the `example` directory also to get things to work.

**Comment by tsiq-swyx** [comment]
hmm. send a PR to improve the docs? i hate it when instructions are
incomplete, but i guess i have enough implicit knowledge now that that
didnt stop me

**Comment by worthlutz** [comment]
OK. I take it that you are confirming that the "publish a dummy version" is not needed.

I will submit a PR as soon as I understand what I am doing well enough to improve the docs.

I think `create-react-library` is going to be a big help to me.
Thanks!

**Comment by tsiq-swyx** [comment]
yea not needed. npm linking is a dark art, i dont know it super well myself.

C-R-L is great!!!

**Comment by transitive-bullshit** [comment]
My understanding is that if you're using `npm >= 6`, it's no longer needed, whereas it was necessary before v6. And it's not necessary at all with yarn.. this kind of nuance is a little difficult to describe in the printout / docs, so I'm very open to suggestions on how to improve things :)

**Comment by transitive-bullshit** [comment]
@worthlutz I just published `v2.3.9` which removes the dummy publish recommendation.

Thanks!
