### ISSUE TITLE
Error starting the example

### ISSUE THREAD

**Issue by Ladvace** [transitive-bullshit/create-react-library#324]
I tried running `npm start` in the **Example** folder but when I do that I get the following error: 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nameOfThePackage@0.0.0 start: `node ../node_modules/react-scripts/bin/react-scripts.js start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nameOfThePackage@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by JoaoLucasGtr** [comment]
@Ladvace I had a similar issue

What I did was:

- deleted the root node_modules directory
- ran `npm i --legacy-peer-deps`
- then `npm i` in the example folder

Hope it helps!

**Comment by Ladvace** [comment]
actually I don't know what I did but at the end I managed to fix it, thanks anyway!
