### ISSUE TITLE
The package changes the name of all the classNames in the application's CSS file

### ISSUE THREAD

**Issue by Matheus-Franco** [transitive-bullshit/create-react-library#326]
Every time the code is compiled, the package changes the name of all the classNames in the application's CSS file (creates a hash), but the className that is passed in each element stays with the initial name.

Example:

**Before compilation:**
```
// index.js
className="input-error"
```

```
//  index.css
.input-error {
    color: red
}
```

**After compilation:**
```
// index.js
className: "input-error"
```

```
//  index.css
._3cawd {
    color: red;
}
```

Can someone help me, please?

**Comment by Omrisamara** [comment]
This is still happening to me, were you able to solve this?
