### ISSUE TITLE
typescript support?

### ISSUE THREAD

**Issue by mmahalwy** [transitive-bullshit/create-react-library#33]
I can probably work on making it happen

**Comment by transitive-bullshit** [comment]
Hey @mmahalwy, thanks for the interest!  I'm definitely planning on getting around to this at some point, but for now, you can check out @kaltsimon's PR #21.

**Comment by transitive-bullshit** [comment]
See #37

**Comment by transitive-bullshit** [comment]
Added in `v2.4.0` 👍
