### ISSUE TITLE
Getting some linting issue

### ISSUE THREAD

**Issue by Fox333-Lab** [transitive-bullshit/create-react-library#350]
I am working on creating a library but one of the js file is giving an linting issue(probably) and this just for the one specific file. I am new to linting and JS, please someone help,below is the screenshot for the same and also the project structure:

the issue:
![image](https://user-images.githubusercontent.com/67701997/128356137-a9abefc5-9e04-4b37-8102-ca56082f1cf1.png)

folder structure:
![image](https://user-images.githubusercontent.com/67701997/128356268-5b9ad4c9-f74e-4d26-8eae-d2f07e11e26e.png)

Thank you in advance

**Comment by yosefbeder** [comment]
I had this problem, too.

First, I tried to solve it by going `.editorconfig` and setting `end_of_line` to `crlf` (If you're using a windows machine).
It worked for some files but didn't for others (I don't know how).

Finally, I decided to ignore the `src` directory by adding `src/` to `.eslintignore`.

**Comment by Fox333-Lab** [comment]
Hi @yosefbeder! editing the _".editorconfig"_  as you mentioned worked for me.....thank you very much for the suggestion, appreciate it a lot 👍

**Comment by yosefbeder** [comment]
You're welcome
