### ISSUE TITLE
Example can't seem to get node-sass to work, even though lib works just fine

### ISSUE THREAD

**Issue by tachyon-ops** [transitive-bullshit/create-react-library#354]
Hi all,

I am having the following error on `my_lib/example` on `yarn start`: 
```ts
Failed to compile.

./src/layout/Layout.module.scss (../node_modules/css-loader/dist/cjs.js??ref--6-oneOf-6-1!../node_modules/postcss-loader/src??postcss!../node_modules/resolve-url-loader??ref--6-oneOf-6-3!../node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-6-4!./src/layout/Layout.module.scss)
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.
```

I have tried to add `node-sass` and `sass` with `yarn add` as well as adding `"node-sass": "link:../node_modules/node-sass` (for both `node-sass` and `sass`). None seems to work and all my tries yield the above error message. Is anyone able to figure what `Node Sass version 6.0.1 is inpompatible with ^4.0.0.` means? Incompatible with what?
Thanks for this awesome react library generator 👍

**Comment by nmpribeiro** [comment]
I had to do substantial changes to the config. Basically, this seems fixed by new `react-scripts` as mentioned [here](https://stackoverflow.com/a/69305209/5954864).
So, I updated my `./package.json` to `"react-scripts": "^4.0.3",`. Nothing broke in the `lib`.

So far, all seems good.
