### ISSUE TITLE
--css-modules false or null doesnt work

### ISSUE THREAD

**Issue by resting** [transitive-bullshit/create-react-library#372]
The generated css in `dist` is still in prefixed with dynamic class names.

Is there anyway to make the option work?

Update:
Moving `--css-modules false` to the beginning before the rest of the options worked.
But `null` still doesn't work properly. It treats all css files as modules css.
So  current state is you can only define true/false, which treats all .css files as either modules css or non modules css.
There's no way to mix them currently although according to the main `microbundle` it should be supported.

**Comment by transitive-bullshit** [comment]
As stated in the readme, this library is no longer maintained and there are better alternatives. See the github readme for more details.
