### ISSUE TITLE
Module isn't creating on Mac OS

### ISSUE THREAD

**Issue by sajanv88** [transitive-bullshit/create-react-library#38]
I followed exactly what it has mentioned in the Readme file but it didn't work. Please refer the screenshot below. 

![screen shot 2018-07-11 at 5 42 48 pm](https://user-images.githubusercontent.com/40479827/42570562-e9d90096-8531-11e8-9d92-b0c5eae03b0d.png)

**Comment by transitive-bullshit** [comment]
Which version of node are you using?  It's likely you need to update to `node >= 8`.

I need to add a printout warning users of this.

**Comment by transitive-bullshit** [comment]
Added a printout in `v2.4.0`. Please upgrade your version of `node` accordingly.
