### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by ahmednooor** [transitive-bullshit/create-react-library#40]
Thank you for this package :)
I was able to create my first react reusable component with this package.
https://github.com/ahmednooor/touchflip-react

Also some feedback.
Everything worked great the first time.
But the second time after updating my code, `npm run deploy` didn't work.
Ultimately I reinstalled the `gh-pages` globally which resolved the issue.
Hope this helps.

Once again Thank You :)

**Comment by transitive-bullshit** [comment]
Thanks for the kind words -- it really helps to keep me motivated 💯 

And congrats on your first react library!!

**Comment by ahmednooor** [comment]
@tsiq-swyx  @transitive-bullshit  thank you very much :)

**Comment by conor** [comment]
@transitive-bullshit cheers mate. Great work!

**Comment by Noitidart** [comment]
Yes thank you!!!

**Comment by markau** [comment]
@transitive-bullshit A clever and well executed project, thank you very much.

**Comment by benkeen** [comment]
Yeah, seriously this is a great tool. Setting everything up can be such a royal pain, this has been absolutely invaluable. Appreciated!!!

**Comment by transitive-bullshit** [comment]
Thanks for the continued support, everyone!

Please star the repo if you haven't already and share with your fellow React peeps 👍

**Comment by jakewies** [comment]
Just came across this and it's awesome 👍 Can't wait to use it for my next project. Starred ⭐️ Nice work @transitive-bullshit !

**Comment by alexdriaguine** [comment]
Just tried this out this weekend and it's awesome! 😁 🎆
