### ISSUE TITLE
Add to CRL readme list

### ISSUE THREAD

**Issue by Silind** [transitive-bullshit/create-react-library#43]
Nice work with this library.
Had the pleasure of bootstrapping a login-modal with this, and it definitely made my life easier!

I'd be cool to have this added to the crl readme list 😁

- [react-login-modal-sm](https://github.com/Silind/react-login-modal-sm) - A customizable React Social Media login modal

**Comment by transitive-bullshit** [comment]
Just added -- thanks! 😁😁
