### ISSUE TITLE
Question about deploying

### ISSUE THREAD

**Issue by remy-poirier** [transitive-bullshit/create-react-library#45]
Hello, 

First of all, thank you for your work, your library is perfectly what I needed !
I have only one problem when I try to run `npm run deploy` to see the page on github pages, I have a weird error saying : 

```
git-upload-pack '.': git-upload-pack: command not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Do you know why I have this error ? I could do all the other stuff (npm publish, work in local, etc...)

I am on Windows if it can help

**Comment by transitive-bullshit** [comment]
We're using [gh-pages](https://github.com/tschaub/gh-pages) to run the deploy under the hood. I'd recommend asking this question with a bit more logging over there.

One thing to check is to make sure your GitHub repository has GitHub Pages enabled.

Good luck!

**Comment by transitive-bullshit** [comment]
Also, please be sure to star this repo if you've found it useful :)

**Comment by remy-poirier** [comment]
Ok that's my bad it was disable, now it works if I directly type `gh-pages -d example/build` from the terminal, but not when I run npm deploy which runs the exact same command lol.

Anyway, it's not related to your library so I will keep my investigations.

Thank you for your job!
