### ISSUE TITLE
Question about default port.

### ISSUE THREAD

**Issue by papaponmx** [transitive-bullshit/create-react-library#50]
What is the default port when runint `yarn start`?

**Comment by transitive-bullshit** [comment]
`yarn start` at the generated template's root will run `rollup` with the watch flag to recompile your source on changes. This doesn't create any server or use any ports.

`yarn start` at the generated template's `example` folder runs a normal version of `create-react-app`, which defaults to port 3000 but will prompt you if there's something already bound to port 3000.

**Comment by papaponmx** [comment]
How do you go about circular references?

**Comment by transitive-bullshit** [comment]
I'm not sure what you're talking about; would you mind providing an example?

In general, any **valid** JavaScript can be bundled by `create-react-library`.

**Comment by transitive-bullshit** [comment]
Closing for now; feel free to re-open if you have more detail on your questions.

Thanks!
