### ISSUE TITLE
ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by franz-see** [transitive-bullshit/create-react-library#54]
I tried creating a library with this tool and I got this error when I ran the project that used that library. The fix seems to be this https://github.com/storybooks/storybook/issues/1320

i.e. remove 'external-helpers' from .babelrc and add it in rollup.config.js

**Comment by franz-see** [comment]
_ | Version
-------- | -------------
Platform | macOS High Sierra (10.13.6)
npm | 6.4.0
node | v10.9.0

**Comment by transitive-bullshit** [comment]
Thanks for the bug report @franz-see.

I haven't been able to reproduce this issue myself, but it appears this has affected quite a few people over at storybook, so I've gone ahead and incorporated the suggested fix.

The whole interplay between `rollup` and `babel`, and `external-helpers` is pretty confusing to me, so I'm not sure which way is "more correct".

Perhaps @emartini, @Rich-Harris, or @Andarist could chime in with a clear best answer?

**Comment by Andarist** [comment]
I can confirm that `external-helpers` should be specified only in `rollup.config.js`. `rollup-plugin-babel` currently changes what `external-helpers` really do - the babel plugin inserts references to global `babelHelpers` object, rollup plugin on the other hand inserts a `import * as babelHelpers from 'fake-helpers-module'` which "shadows" inserted global reference and later hijacks the request to this fake module and resolve it to a in memory module with all helpers in it and rely on tree-shaking to remove unused ones.

So those shenanigans happen to dedupe inserted helpers and use only a single copy of each in a flat bundle.

The good thing is that rollup-plugin-babel@4 (upcoming, targeting babel@7) will do this deduping without forcing `external-helpers` on you.

**Comment by transitive-bullshit** [comment]
Thanks for the thorough answer @Andarist!

@franz-see just released this fix in `v2.6.1`.
