### ISSUE TITLE
I made a thing with this

### ISSUE THREAD

**Issue by jbccollins** [transitive-bullshit/create-react-library#55]
This library is fking awesome. Thanks for maintaining it!

I made this small thingy with it: https://github.com/jbccollins/react-gradient-scroll-indicator

If you want to add this to the list of projects created using this library in the readme feel free. No worries if not. Cheers!

**Comment by transitive-bullshit** [comment]
Thanks, dude -- really appreciate the props :)

Added to the readme 👍
