### ISSUE TITLE
SASS support by default?

### ISSUE THREAD

**Issue by jbccollins** [transitive-bullshit/create-react-library#56]
Would you be on board with supporting SASS / SASS modules by default?

**Comment by transitive-bullshit** [comment]
It seems the only [change](https://github.com/egoist/rollup-plugin-postcss#with-sassstylusless) necessary would be to add `node-sass` as a dev dependency, correct?

If we're going to do this, we'd probably also add `stylus` and `less` as dev deps, though I'm hesitant to add extra deps by default that many people won't use, especially with the prevalence of `css-in-js` these days.

I could go either way. Maybe this would be better solved with a simple addition to the docs FAQ since it's so easy for the end-user opt into themselves?

**Comment by jbccollins** [comment]
Yeah the only changes would be to install `node-sass` as a dev dependency, rename `styles.css` to `styles.scss` then update the import statement with that rename.

But yeah I see your point about "if we support one then we probably should support all" and I agree that's probably outside the scope of this project. Your call on whether you want it in the README :)

**Comment by transitive-bullshit** [comment]
Tracking in #57

**Comment by MikelArnaiz** [comment]
@transitive-bullshit the docs of [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) you referred to are for `v1.0`+

> You are viewing the docs for v1.0, for v0.5 please see [here](https://github.com/egoist/rollup-plugin-postcss/tree/0.5).

`create-react-library@2.6.6` has as dependency `rollup-plugin-postcss-modules@1.0.8` which has as a dependency `rollup-plugin-postcss@0.5.5`.

How else can we support `scss` files?

**Comment by wendzhue** [comment]
I can import SASS files in the demo in `example`.

**Comment by rosinghal** [comment]
@wendzhue Same here. Did you got any solution?
(I have installed `node-sass`)

**Comment by HenriqueFadoni** [comment]
Same here, and I have all installed. That's a pain in the ass, I need to restart the server all the time to see new changes.

**Comment by alexjtupper** [comment]
Not sure if this helps but here's a version of this problem that I solved that means I can now use SASS in the custom library (tl;dr: add `node-sass` as a dependency, AND add `--css-modules false` option to the `"build"` and `"start"` scripts in `package.json`)


**Steps to replicate the problem:**
- Create a library (`my-library`) using `npx create-react-library`
- Create a component called `MyComponent` and import into this component's definition a `MyComponent.scss` SASS style
- Install `node-sass` and build the library successfully using `npm run start`
- Install the library as a dependency in a neighbouring react app project: `npm install --save ../my-library`
- In one of the react files in this react app project, import the component: `import {MyComponent} from 'my-library'` and, in the top-level App.js file, import the library's styles: `import 'my-library/dist/index.css'`


**Problem:**
The styles of the custom component don't appear to take any effect.
The `./dist/index.css` CSS that is generated by microbundle-crl in `my-library` has class names, etc, suffixed a la css modules


**Solution:**
In `./package.json`, add the following option to both the `"start"` and `"build"` scripts (`microbundle-crl`) and re-run the script:
`--css-modules false`

Now, the styles in `./dist/index.css` take effect in my react project.
