### ISSUE TITLE
Getting an error in the example project

### ISSUE THREAD

**Issue by stevensacks** [transitive-bullshit/create-react-library#58]
```bash
npm ERR! path /Users/steven/Development/react-components/example/node_modules/.staging/react-components-b0ed9029/node_modules/@babel/code-frame
```

This happens when I try to run `npm i` in the example project.

Any idea what might be causing this?

**Comment by stevensacks** [comment]
If I remove this dependency:

```bash
"react-components": "file:..",
```

Then `npm i` runs fine. But obviously, I need that or I can't test my library.

**Comment by transitive-bullshit** [comment]
I've run into this very occasionally as well. It's apparently an issue with `npm`, that can be resolved most of the time by removing the node_modules, clearing your `npm` cache, and then reinstalling.

```bash
rm -rf node_modules
npm cache clean -f
npm install
```

**Comment by transitive-bullshit** [comment]
Also, which platform and version of node / npm / create-react-library are you using?

**Comment by stevensacks** [comment]
I installed @babel/code-frame and the problem went away.

```
npm install --save-dev @babel/code-frame
```

Not sure if this is ideal but it worked. I'll try your solution, too.

**Comment by stevensacks** [comment]
Nevermind, when I ran the example, I got this

```
Module not found: Can't resolve 'core' in '/Users/steven/Development/react-components/dist'
```

**Comment by transitive-bullshit** [comment]
Can you point me to your source?

It looks like your source component is using a non-standard import or something.

**Comment by stevensacks** [comment]
Tried your suggestion, got the same error about code-frame.

npm 6.4.0
node 9.11.1

**Comment by transitive-bullshit** [comment]
If you have any local `package-lock.json` files, try removing them too.

**Comment by stevensacks** [comment]
I figured it out. I ran node-check-updates and it updated the following packages. Rolled back and it worked.

These are the latest versions and they don't work:
```
"babel-eslint": "^9.0.0",
"rollup": "^0.65.0",
"rollup-plugin-babel": "^4.0.1",
```

Also, that can't resolve 'core' was my fault - a bad import.

**Comment by transitive-bullshit** [comment]
Perhaps this is related to today's release of Babel 7? https://babeljs.io/blog/2018/08/27/7.0.0
