### ISSUE TITLE
cannot spawn sh: No such file or directory

### ISSUE THREAD

**Issue by sag1v** [transitive-bullshit/create-react-library#59]
Trying to `npm run deploy` and getting:  
>error: cannot spawn sh: No such file or directory
>fatal: unable to fork

On windows 7 sp1 64bit.

Any idea why i'm getting this?

**Comment by transitive-bullshit** [comment]
It's trying to run a bash command on Windows for some reason.

I haven't seen this before and unfortunately don't have a Windows machine to test on.

**Comment by sag1v** [comment]
I managed to solve this somehow (after several solutions found online) but i can't remember which one was it.  
I'm closing this issue unless you want to keep it open.
