### ISSUE TITLE
add support for prettier with eslint

### ISSUE THREAD

**Issue by sag1v** [transitive-bullshit/create-react-library#60]
Is there any way to configure prettier to be part of the development or build process of `create-react-library` ?  

When maintaining a library it's often get frustrating when your code style get mixed patterns, especially when you need to merge PR's.  
[prettier](https://github.com/prettier/prettier) and [prettier-eslint](https://github.com/prettier/prettier-eslint) can greatly help with this issue.  
You can configure it to `--fix` on save or before deploy etc.. thus ensuring that your code style stays consistent no matter what.

**Comment by transitive-bullshit** [comment]
There's no built-in support for prettier at this time. In general, we're trying to keep the base options as minimal as possible.

There's nothing stopping you from adding prettier on top of the default template.

**Comment by sag1v** [comment]
Yeah i managed to do it eventually.
