### ISSUE TITLE
[feature request] Add docz as the documentation tool

### ISSUE THREAD

**Issue by sag1v** [transitive-bullshit/create-react-library#62]
Don't know if you are familiar with [docz ](https://github.com/pedronauck/docz), but it takes only couple of minutes to play with it and understand the huge potential it has.  

I'm using it with a new library i'm working on (built with `create-react-library`) and the documentations and example are a breeze to write.  

Maybe consider integrating with it, it wasn't too hard for me to implement with CRL and i'm sure that [pedronauck](https://github.com/pedronauck) (the author) would be happy to assist if needed.

**Comment by transitive-bullshit** [comment]
Docz is indeed awesome and gaining popularity fast. I'd welcome @pedronauck's thoughts on this we well 😄 

On the other hand, I'd prefer to try and keep the core of CRL as small and focused as possible. Perhaps docz integration could be added to the forthcoming FAQ #57?

**Comment by sag1v** [comment]
> On the other hand, I'd prefer to try and keep the core of CRL as small and focused as possible

Fir enough.

> Perhaps docz integration could be added to the forthcoming FAQ #57?

Already added as a comment 🤓

**Comment by sag1v** [comment]
By the way, if you need an example of how i implemented it on [my library](https://github.com/sag1v/react-elastic-carousel)
