### ISSUE TITLE
create-react-library failing at yarn install

### ISSUE THREAD

**Issue by shalomsam** [transitive-bullshit/create-react-library#64]
The create-react-library errors out at yarn install and link, but works fine with NPM.

Here is the error it coughed out - 

Copying default template to /Users/shalom.s/Sites/shalomsam-new/projects/react-particles
✖ Running yarn install and yarn link
{ Error: Command failed: /bin/sh -c yarn install
warning react-scripts > babel-preset-react-app > babel-preset-env > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning react-scripts > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
error eslint@5.6.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
error Found incompatible module

yarn install v1.7.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at makeError (/Users/shalom.s/.nvm/versions/node/v8.9.3/lib/node_modules/create-react-library/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/Users/shalom.s/.nvm/versions/node/v8.9.3/lib/node_modules/create-react-library/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: 'yarn install v1.7.0\ninfo No lockfile found.\n[1/5] Validating package.json...\n[2/5] Resolving packages...\n[3/5] Fetching packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr: 'warning react-scripts > babel-preset-react-app > babel-preset-env > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning react-scripts > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning react-scripts > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning react-scripts > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nwarning react-scripts > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nerror eslint@5.6.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".\nerror Found incompatible module\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c yarn install',
  timedOut: false,
  killed: false }

**Comment by transitive-bullshit** [comment]
This error is saying that your `node` version is incompatible with a dependency, specifically `eslint`.

I would recommend that you upgrade your version of Node.

This could happen with either `npm` or `yarn`; I think it's just a coincidence that `yarn` chose slightly different versions of dependencies and ran into this issue.

**Comment by transitive-bullshit** [comment]
Closing now as answered; please feel free to re-open this issue if you're still having trouble 😄

**Comment by kraisorns** [comment]
@transitive-bullshit I got error something like this

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

```
node: 10.4.1
yarn: 1.7.0
```
