### ISSUE TITLE
Easier usage docs

### ISSUE THREAD

**Issue by wuweiweiwu** [transitive-bullshit/create-react-library#69]
with npm v5.2+  you can use `npx create-react-library`

with npm v6+  you can use `npm init react-library`

with Yarn 0.25+ you can use `yarn create react-library`

**Comment by transitive-bullshit** [comment]
Thanks for the suggestion @wuweiweiwu 👍

The `npm init` pattern is quickly becoming a standard, but until it is more mature and requires less caveats about specific versions of `npm / yarn`, I think it's best to leave the installation instructions as-is.

More advanced users will recognize that you can use the `npm init` standard and circumvent the global installation.

**Comment by wuweiweiwu** [comment]
makes sense!
