### ISSUE TITLE
Crazy preferBuiltins stuff

### ISSUE THREAD

**Issue by fix-me** [transitive-bullshit/create-react-library#78]
Hi,

at first I would like to thank you for this beautiful package compilation!

Nevertheless I have some troubles and a single line of code breaks everything.
I want to import Swagger from 'swagger-client' package which makes me crazy.

So I simply added it through `npm i swagger-client` and inserted `import Swagger from 'swagger-client';` in the library **'src/index.js'**. `npm start` and baam, broken.

Do you have any suggestion? What am I missing?

Thank you very much for investigation!

@ref: https://github.com/transitive-bullshit/react-modern-library-boilerplate/issues/23#issue-366879742

**Comment by transitive-bullshit** [comment]
Can you provide more debugging info or preferably a github repo which reproduces the error?

When you say "broken", what is the actual error message? What happens specifically?

**Comment by fix-me** [comment]
Oh, yes. I think this is a swagger-js lib related issue because others like swagger-parser-js are working fine. But maybe some hardening could be applied: https://github.com/swagger-api/swagger-js/issues/1391#issuecomment-427291040
