### ISSUE TITLE
Jest tests in ./example

### ISSUE THREAD

**Issue by edwardpayton** [transitive-bullshit/create-react-library#82]
Hi there,

I have been trying to set up Jest tests for my component. [This comment](https://github.com/transitive-bullshit/create-react-library/issues/34#issuecomment-402782596) recommends adding tests to the example directory, which makes sense because they then have access to the react scripts test support. 

Could I have an example of this setup? 

The Material UI example has a test in the [src directory](https://github.com/transitive-bullshit/react-modern-library-boilerplate/tree/feature/material-ui/src), so goes against the recommended advice. I've tried to get it to work and but after several hours of console errors I don't seem to be getting anywhere. 

Thanks in advance.

(apologies for opening multiple issues. I clicked the wrong button)

**Comment by transitive-bullshit** [comment]
`v3` adds support for jest tests in the top-level `src/` directory as well as in the CRA `example/` directory.
