### ISSUE TITLE
Tests runs only once instead of watch mode

### ISSUE THREAD

**Issue by spredemann** [transitive-bullshit/create-react-library#9]
As the title says. Just tried with a clean copy to make sure I hadn't messed with anything. I guess the expected behavior was that the tests would run continuously? If not I'd appreciate hints on how to achieve that since I don't quite get what the `CI=1` means in the test command.

**Comment by transitive-bullshit** [comment]
Yeah, I had switched off the watch functionality with the `CI=1` so we could run tests in without it hanging forever.

You can either just remove that `CI=1` and/or we should add a `test:watch` script that runs it without that flag.

**Comment by spredemann** [comment]
Thanks for being so responsive!

Removing `CI=1` throws a bunch of errors.

**Comment by transitive-bullshit** [comment]
Hmmm, it works for me on a few test libraries I've created.

It's just calling `react-scripts test --env=jsdom` under the hood, so I'd suggest searching for your errors on their repo.

**Comment by spredemann** [comment]
You're right. Seems to be a problem on [their end ](https://github.com/facebook/create-react-app/issues/4045). Same errors.
