### ISSUE TITLE
Switch back to `rollup-plugin-postcss-modules`?

### ISSUE THREAD

**Issue by flying-sheep** [transitive-bullshit/create-react-library#92]
Hi, I fixed the bug that was the reason for #88

You could have fixed it by removing `modules: true` (since my plugin always does modules) but I understand that my error message was confusing.

The main difference between mine and `rollup-plugin-postcss` is that using `writeDefinitions`, my plugin has typescript support.

**Comment by transitive-bullshit** [comment]
This should be fixed now with the latest `v3` release as we're now using `microbundle` to handle everything for us.

Please open a new issue if you're still seeing errors.
