### ISSUE TITLE
CLI not working globally after installation.

### ISSUE THREAD

**Issue by padsbanger** [transitive-bullshit/create-react-library#95]
Hello, after running in terminal: `npm install -g create-react-library` and trying to use it `create-react-library test` I get `command not found: create-react-library`.

I am running OSX 10.13, Node 10.12 and NPM 6.4.1

**Comment by zachwolf** [comment]
What version of `create-react-library` was installed? Are you able to install and run similar tools like `create-react-app`?

**Comment by transitive-bullshit** [comment]
Thanks @zachwolf 👍 

One additional question: can you uninstall globally and then run `npm install -g create-react-library --verbose` and paste the output below?

**Comment by EvanBurbidge** [comment]
Getting the same issue.

**Comment by transitive-bullshit** [comment]
@EvanBurbidge most likely it's due to your version of node.js. Try using `node >= 8`.
