### ISSUE TITLE
Proposal: Process filenames from template via Handlebars

### ISSUE THREAD

**Issue by bmuenzenmeyer** [transitive-bullshit/create-react-library#96]
This library is a wonderful tool, thanks!

Wondering if you'd be interested in processing all template files (or a subset, if that makes sense) through handlerbars.

Use case: I want to generate a new library `MyAwesomeButton`, and I want files inside `src/` to be called `MyAwesomeButton.js` and `MyAwesomeButton.test.js`

Handlebar keys are not valid file specifiers, so one cannot simply have a template file called `{{name}}.js`. If this proposal is accepted, we will need to solve for this.

Thoughts? Interest from the community?

**Comment by bmuenzenmeyer** [comment]
Actually, `{{name}}.js` is valid, so the effort would be minimal.

**Comment by transitive-bullshit** [comment]
I definitely appreciate the work you did on this, but maintenance time is always an issue on OSS projects and this complicates things a bit, I'm going to go ahead and close this.

Feel free to reopen if you feel strongly.

Thanks!
