### ISSUE TITLE
peerDependencies required for tests

### ISSUE THREAD

**Issue by rap2hpoutre** [transitive-bullshit/create-react-library#98]
I can add `peerDependencies` to my `package.json`. But it makes the tests fails, example:

```
> yarn test

yarn run v1.10.1
$ cross-env CI=1 react-scripts test --env=jsdom
 FAIL  src/test.js
  · Test suite failed to run

    Cannot find module '@appbaseio/reactivesearch' from 'MultiList.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/MultiList.js:2:23)
```

Is there a way to make the tests work with peerDependencies?

You can see the error here: https://circleci.com/gh/betagouv/pop-shared/1

**Comment by tchalvak** [comment]
I believe a common approach here is to put a package recommendation in peerDependencies and the actual in-use package in devDependencies. This is so that a consumers of your library can handle their own react versioning, and yet your CI tests can use whatever version you are currently using.

**Comment by rap2hpoutre** [comment]
Ok thank you!
